polish static toybox

diff --git a/hybris-installer/META-INF/com/google/android/update-binary b/hybris-installer/META-INF/com/google/android/update-binary
--- a/hybris-installer/META-INF/com/google/android/update-binary
+++ b/hybris-installer/META-INF/com/google/android/update-binary
@@ -68,7 +68,6 @@ if [ `cat /system_root/system/build.prop | grep lineage.build.version= | cut -d'
 	fi
 	log "About to perform forced flash of SFOS"
 fi
-[ -f /system/bin/toybox ] || abort 8 "Your ROM doesn't ship with toybox; extracting of SFOS rootfs isn't possible!"
 if [ -f $ROOT/etc/os-release ]; then
 	if [ ! -f /tmp/sfos_fresh_confirm ]; then
 		touch /tmp/sfos_fresh_confirm
@@ -128,11 +127,13 @@ log "Extracting package '$ZIPFILE'..."
 mkdir -p $FILES/
 unzip -o "$ZIPFILE" -x META-INF/* -d $FILES/
 
+PATH="$FILES/bin:$PATH"
+
 log "Extracting SFOS rootfs..."
 ARCHIVE="$FILES/sfos-rootfs.tar.bz2"
 rm -rf $ROOT/
 mkdir -p $ROOT/
-$FILES/toybox tar -xj -f $ARCHIVE -C $ROOT/ || abort 10 "Couldn't extract SFOS rootfs!"
+tar -xj -f $ARCHIVE -C $ROOT/ || abort 10 "Couldn't extract SFOS rootfs!"
 rm $ARCHIVE
 
 log "Fixing up init scripts..."
@@ -144,17 +145,6 @@ rm $ROOT/init.extraenv.armeabi-v7a.rc
 log "Disabling forced encryption in vendor fstab..."
 (umount /vendor &> /dev/null; mount -o rw /vendor && sed "s/fileencryption/encryptable/" -i /vendor/etc/fstab.qcom) || log "Couldn't disable forced encryption!"
 umount /vendor &
-
-if [[ "$TARGET_LOS_VER" = "16.0" && ! -f $ROOT/lib/systemd/system/mnt-vendor-persist.mount ]]; then
-	log "Mount unit for persist not found; copying current /persist to rootfs..."
-	mkdir -p $ROOT/mnt/vendor/persist /persist
-	if mount $PARTITION_PERSIST /persist; then
-		cp -a /persist/ $ROOT/mnt/vendor/
-		umount /persist
-	else
-		log "Couldn't mount $PARTITION_PERSIST! Skipping copying..."
-	fi
-fi
 
 if [ "$FORCE_REINSTALL" = "0" ]; then
 	log "Backing up droid-boot image..."
