initial adaptation

diff --git a/hybris-installer/META-INF/com/google/android/update-binary b/hybris-installer/META-INF/com/google/android/update-binary
--- a/hybris-installer/META-INF/com/google/android/update-binary
+++ b/hybris-installer/META-INF/com/google/android/update-binary
@@ -21,7 +21,7 @@ set_progress() { echo -e "set_progress $1\n" > $OUTFD; }
 ui_print() { [ -z "$1" ] && echo -e "ui_print  \nui_print" > $OUTFD || echo -e "ui_print $@\nui_print" > $OUTFD; }
 
 # Log some text ($1) for script debugging
-log() { echo "hybris-installer: $@"; }
+log() { ui_print "hybris-installer: $@"; }
 
 # Remove package residue files from /tmp and unmount partitions
 cleanup() { log "Cleaning up..."; umount /system; rm -rf $FILES/; }
@@ -58,10 +58,10 @@ invalid_device && CURRENT_DEVICE=`getprop ro.build.product`
 	(mount | grep -q "/cache.*ext4" || abort 1 "Cache is NOT formatted as ext4; check out 'Wipe > Advanced' from TWRP!") ||
 	log "Couldn't mount /cache! Is this an A/B device by any chance?"
 (mount | grep -q /data || mount /data) || abort 2 "Couldn't mount /data; running e2fsck and rebooting may help."
-mount | grep -q "/data.*ext4" || abort 3 "Data is NOT formatted as ext4; check out 'Wipe > Advanced' from TWRP!"
+#mount | grep -q "/data.*f2fs" || abort 3 "Data is NOT formatted as ext4; check out 'Wipe > Advanced' from TWRP!"
 
 # Treble
-if [ $TARGET_DEVICE == "enchilada" ] || [ $TARGET_DEVICE == "fajita" ]; then # TWRP on these devices doesn't handle system_is_root properly, need to fix it up manually
+if [ $TARGET_DEVICE == "enchilada" ] || [ $TARGET_DEVICE == "fajita" ] || [ $TARGET_DEVICE == "river" ]; then # TWRP on these devices doesn't handle system_is_root properly, need to fix it up manually
 	log "Device is system-as-root, ensuring /system_root and /system are mounted correctly"
 	umount /system
 	umount /system_root
@@ -142,7 +142,7 @@ log "Extracting SFOS rootfs..."
 ARCHIVE="$FILES/sfos-rootfs.tar.bz2"
 rm -rf $ROOT/
 mkdir -p $ROOT/
-/system/bin/toybox tar -xj -f $ARCHIVE -C $ROOT/ || abort 10 "Couldn't extract SFOS rootfs!"
+/system/bin/toybox tar --numeric-ownder -xjf $ARCHIVE -C $ROOT/ || abort 10 "Couldn't extract SFOS rootfs!"
 rm $ARCHIVE
 
 log "Cloning /persist from Android to prevent issues with WiFi when dual booting"
