add sensors service fix-up

diff --git a/hybris-installer/META-INF/com/google/android/update-binary b/hybris-installer/META-INF/com/google/android/update-binary
--- a/hybris-installer/META-INF/com/google/android/update-binary
+++ b/hybris-installer/META-INF/com/google/android/update-binary
@@ -21,7 +21,7 @@ set_progress() { echo -e "set_progress $1\n" > $OUTFD; }
 ui_print() { [ -z "$1" ] && echo -e "ui_print  \nui_print" > $OUTFD || echo -e "ui_print $@\nui_print" > $OUTFD; }
 
 # Log some text ($1) for script debugging
-log() { ui_print "hybris-installer: $@"; }
+log() { echo "hybris-installer: $@"; }
 
 # Remove package residue files from /tmp and unmount partitions
 cleanup() { log "Cleaning up..."; umount /system; rm -rf $FILES/; }
@@ -31,26 +31,22 @@ abort() { ui_print "E$1: $2"; cleanup; exit $1; }
 
 # <<< TWRP init <<<
 
-# >>> Custom functions >>>
-
-# Verify device boardname validity (e.g. not unset, no spaces / uppercase chars)
-invalid_device() { [[ -z "$CURRENT_DEVICE" || "$CURRENT_DEVICE" = *" "* || `echo "$CURRENT_DEVICE" | grep -q [A-Z]` ]]; }
-
-# <<< Custom functions <<<
-
 # Constants & variables
 VERSION="%VERSION%" # e.g. "3.2.0.12 (Torronsuo)"
 TARGET_LOS_VER="%LOS_VER%" # e.g. "16.0"
 TARGET_DEVICE="%DEVICE%" # e.g. "cheeseburger"
-CURRENT_DEVICE=`getprop ro.omni.device`
+CURRENT_DEVICE=`getprop ro.product.device`
+START_SECS=`date +'%s'`
 ROOT="/data/.stowaways/sailfishos"
 FORCE_REINSTALL=0
+PARTITION_PREFIX="/dev/block/bootdevice/by-name"
+PARTITION_BOOT="$PARTITION_PREFIX/boot"
+PARTITION_VENDOR="$PARTITION_PREFIX/vendor"
+PARTITION_PERSIST="$PARTITION_PREFIX/persist"
 
 # >>> Sanity checks >>>
 
 # Device
-invalid_device && CURRENT_DEVICE=`getprop ro.product.device`
-invalid_device && CURRENT_DEVICE=`getprop ro.build.product`
 [ "$CURRENT_DEVICE" != "$TARGET_DEVICE" ] && abort 7 "This package is for '$TARGET_DEVICE' devices; this is a '$CURRENT_DEVICE'."
 
 # ext4 check for /data (& /cache)
@@ -58,17 +54,11 @@ invalid_device && CURRENT_DEVICE=`getprop ro.build.product`
 	(mount | grep -q "/cache.*ext4" || abort 1 "Cache is NOT formatted as ext4; check out 'Wipe > Advanced' from TWRP!") ||
 	log "Couldn't mount /cache! Is this an A/B device by any chance?"
 (mount | grep -q /data || mount /data) || abort 2 "Couldn't mount /data; running e2fsck and rebooting may help."
-#mount | grep -q "/data.*f2fs" || abort 3 "Data is NOT formatted as ext4; check out 'Wipe > Advanced' from TWRP!"
+mount | grep -q "/data.*ext4" || abort 3 "Data is NOT formatted as ext4; check out 'Wipe > Advanced' from TWRP!"
 
 # Treble
-if [ $TARGET_DEVICE == "enchilada" ] || [ $TARGET_DEVICE == "fajita" ] || [ $TARGET_DEVICE == "river" ]; then # TWRP on these devices doesn't handle system_is_root properly, need to fix it up manually
-	log "Device is system-as-root, ensuring /system_root and /system are mounted correctly"
-	umount /system
-	umount /system_root
-	mount /dev/block/bootdevice/by-name/system /system_root || abort 99 "Failed to mount system to /system_root"
-	mount -o bind /system_root/system /system || abort 98 "Failed to bind mount /system_root/system to /system"
-	log "Successfully fixed /system mountpoint, toybox should work properly now..."
-fi
+[ -r $PARTITION_VENDOR ] || abort 4 "A vendor partition doesn't exist; you need to do an OTA from OxygenOS 5.1.5 to 5.1.6!"
+
 # Android
 (mount | grep -q /system || mount /system) || abort 5 "Couldn't mount /system!"
 if [ `cat /system/build.prop | grep lineage.build.version= | cut -d'=' -f2` != "$TARGET_LOS_VER" ]; then
@@ -98,9 +88,9 @@ rm -f /tmp/sfos_f{la,re}sh_confirm
 set_progress 0
 
 # Calculate centering offset indent on left
-offset=`echo -n $VERSION | wc -m` # Character length of the version string
-offset=`expr 52 - 23 - $offset`   # Remove constant string chars from offset calculation
-offset=`expr $offset / 2`         # Get left offset char count instead of space on both sides
+offset=`echo -n $VERSION | wc -m 2> /dev/null` # Character length of the version string
+offset=`expr 52 - 23 - $offset`                # Remove constant string chars from offset calculation
+offset=`expr $offset / 2`                      # Get left offset char count instead of space on both sides
 
 # Build the left side indentation offset string
 for i in `seq 1 $offset`; do indent="${indent} "; done
@@ -142,18 +132,8 @@ log "Extracting SFOS rootfs..."
 ARCHIVE="$FILES/sfos-rootfs.tar.bz2"
 rm -rf $ROOT/
 mkdir -p $ROOT/
-/system/bin/toybox tar --numeric-owner -xjf $ARCHIVE -C $ROOT/ || abort 10 "Couldn't extract SFOS rootfs!"
+/system/bin/toybox tar -xj -f $ARCHIVE -C $ROOT/ || abort 10 "Couldn't extract SFOS rootfs!"
 rm $ARCHIVE
-
-log "Cloning /persist from Android to prevent issues with WiFi when dual booting"
-mkdir /persist
-mount /dev/block/bootdevice/by-name/persist /persist
-mkdir -p /data/.stowaways/sailfishos/mnt/vendor/persist
-cp -r /persist/* $ROOT/mnt/vendor/persist/
-log "Disabling /mnt/vendor/persist mount point"
-ln -s /dev/null $ROOT/etc/systemd/system/mnt-vendor-persist.mount
-log "Deleting wlan_mac.bin to ensure MAC gets loaded from firmware"
-rm /data/.stowaways/sailfishos/mnt/vendor/persist/wlan_mac.bin
 
 log "Fixing up init scripts..."
 sed -e "/extraenv/s/^/#/g" -e "/import \/init.\${ro.hardware}.rc/s/^/#/" -e "/ro.zygote/s/^/#/g" -e "/start update_verifier/s/^/#/g" \
@@ -161,30 +141,69 @@ sed -e "/extraenv/s/^/#/g" -e "/import \/init.\${ro.hardware}.rc/s/^/#/" -e "/ro
     -i $ROOT/init.rc || log "Couldn't fix-up init script!"
 rm $ROOT/init.extraenv.armeabi-v7a.rc
 
+log "Fixing up sensors service permissions..."
+(umount /vendor &> /dev/null; mount -o rw /vendor && cp $FILES/init.qcom.rc /vendor/etc/init/hw/) || log "Couldn't fix-up sensors service"
+umount /vendor &
+
 log "Disabling forced encryption in vendor fstab..."
 (umount /vendor &> /dev/null; mount -o rw /vendor && sed "s/fileencryption/encryptable/" -i /vendor/etc/fstab.qcom) || log "Couldn't disable forced encryption!"
 umount /vendor &
 
+if [[ "$TARGET_LOS_VER" = "16.0" && ! -f $ROOT/lib/systemd/system/mnt-vendor-persist.mount ]]; then
+	log "Mount unit for persist not found; copying current /persist to rootfs..."
+	mkdir -p $ROOT/mnt/vendor/persist /persist
+	if mount $PARTITION_PERSIST /persist; then
+		cp -a /persist/ $ROOT/mnt/vendor/
+		umount /persist
+	else
+		log "Couldn't mount $PARTITION_PERSIST! Skipping copying..."
+	fi
+fi
+
 if [ "$FORCE_REINSTALL" = "0" ]; then
 	log "Backing up droid-boot image..."
-	dd if=/dev/block/bootdevice/by-name/boot of=$ROOT/boot/droid-boot.img
+	dd if=$PARTITION_BOOT of=$ROOT/boot/droid-boot.img bs=4m
 elif [ -f /tmp/droid-boot.img ]; then
 	log "Moving back droid-boot image..."
 	mv /tmp/droid-boot.img $ROOT/boot/
 fi
 
 log "Writing hybris-boot image..."
-dd if=$ROOT/boot/hybris-boot.img of=/dev/block/bootdevice/by-name/boot_a || abort 11 "Couldn't write Hybris boot image!"
+dd if=$ROOT/boot/hybris-boot.img of=$PARTITION_BOOT bs=4m || abort 11 "Couldn't write Hybris boot image!"
 
-log "Applying patches"
-cd $FILES/patches #apply-patches has to be run with PWD be it's working directory
-sh apply-patches.sh $ROOT #directory of the SFOS install must be passed as first param
+log "Symlinking boot images to /sdcard..."
+ln -s $ROOT/boot/droid-boot.img /sdcard/
+ln -s $ROOT/boot/hybris-boot.img /sdcard/
 
 # <<< Script <<<
 
 # Succeeded.
 log "Sailfish OS installed successfully."
-ui_print "            All done, enjoy your new OS!"
+
+# Prepare string for elapsed install time
+end_secs=`date +'%s'`
+elapsed_secs=`expr $end_secs - $START_SECS`
+time_string="" # e.g. "3m 32s"
+if [ "$elapsed_secs" -gt 60 ]; then
+	time_mins=`expr $elapsed_secs / 60`
+	time_secs=`expr $elapsed_secs - $time_mins \* 60`
+	if [ "$time_secs" -gt 0 ]; then
+		time_string="${time_mins}m ${time_secs}s"
+	else
+		time_string="${time_mins}m"
+	fi
+else
+	time_string="${elapsed_secs}s"
+fi
+
+# Center the "All done" text
+offset=`echo -n $time_string | wc -m 2> /dev/null`
+offset=`expr 52 - 33 - $offset`
+offset=`expr $offset / 2`
+indent=""
+for i in `seq 1 $offset`; do indent="${indent} "; done
+
+ui_print "${indent}All done in ~${time_string}, enjoy your new OS!"
 ui_print
 cleanup
 exit 0
